### ISSUE TITLE
Why am I unable to active this plugin?

### ISSUE THREAD

**Issue by Mangavj** [f-b-g-m/Clarity-Manga-Reader#1]
Why am I unable to active this plugin?There is an error with it
 
*Plugin could not be activated because it triggered a fatal error.
*Fatal error: Can't use method return value in write context in /home/u635404632/public_html/wp-content/plugins/Clarity-Manga-Reader-master/public/class-clarity-manga-reader-public.php on line 118
--Just so you can fix bugs early and send the complete plugin via this email address: # 
THANKS. :D

**Comment by f-b-g-m** [comment]
The error is caused because you're using a php version lower than 5.5

**Comment by f-b-g-m** [comment]
I changed it so it should work with 5.3 and up.
