### ISSUE TITLE
How to change the term/taxonomy ?

### ISSUE THREAD

**Issue by madmax124** [f-b-g-m/Clarity-Manga-Reader#2]
Any possibility of changing the taxonomy i.e "manga" to "comic" ?

**Comment by f-b-g-m** [comment]
Not directly, but you can disable the manga post type on the plugins settings and [make your own](https://codex.wordpress.org/Function_Reference/register_post_type), with a custom rewrite. Or use [pods](https://wordpress.org/plugins/pods/) to create it using a user interface.

In both cases the post type name has to be **manga** and comic will be your rewrite.

**Comment by madmax124** [comment]
Ok thank you.
