### ISSUE TITLE
How to add chapters with decimals?

### ISSUE THREAD

**Issue by kosao** [f-b-g-m/Clarity-Manga-Reader#5]
How do you add chapters with decimals (e.g. chapter 3.5)?  They are for "specials" and omakes.

**Comment by f-b-g-m** [comment]
@kosao you must alter the table structure. 
If you have phpmyadmin go to the database, wp_cmr_chapters table and select the structure tab at the top, then click change for the chapter_number row and change its type to varchar in the drop down and set a length (50 should be enough).

**Comment by f-b-g-m** [comment]
But you shouldn't use the plugin, it's not well written, has bugs probably and i didn't test it with lots of chapters . For example on the one i work now i added 1000 chapters and it took 13 seconds to load a page with all of them. I managed to get the load time to less than a second with caching, but i still got to tweak some things.
In this plugin I didn't do this.

**Comment by kosao** [comment]
I'll be waiting for the new one then. I just installed processwire yesterday and I'm loving it! I can't wait your new manga reader comes out.

**Comment by fbg13** [comment]
@kosao the new reader is on github if you're still interested.
https://github.com/fbg13/WireManga
https://github.com/fbg13/WireMangaTheme

There are still some parts I need to figure out, but you can check it out. If you encounter any problems do let me know.
